### ISSUE TITLE
Missing css handlers

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/reviews-and-ratings#23]
**Describe the bug**
Hi! We need some css handlers to customize the login link in the reviews app. I've attached a printscreen to better understand the issue.

**To Reproduce**

1. Install reviews-and-ratings app
2. Try to customize the links color for the <a> tag inside .writeReviewContainer

**Screenshots**
![image](https://user-images.githubusercontent.com/42587916/83125758-99b33b00-a0e0-11ea-953a-233dc674a511.png)

**Comment by polishq** [comment]
Added in new version (1.6.1). Please install and test.

**Comment by doruradu** [comment]
Thank you!
