### ISSUE TITLE
Inaccuracy in cpu request

### ISSUE THREAD

**Issue by valentino-amadeus** [vtex-apps/reviews-and-ratings#63]
**Describe the bug**
The value [added](https://github.com/vtex-apps/reviews-and-ratings/pull/62) to your service.json as cpu request is inaccurate by a factor of `10`: if you want to request `250m` of CPU, you should put `25` into the [value field](https://github.com/vtex-apps/reviews-and-ratings/blob/master/dotnet/service.json#L6) of your service.json. More information on that [here](https://www.notion.so/vtexhandbook/How-to-set-up-the-service-json-on-your-node-app-83a6c3c67503415c872f51412eed74d6#8aa4deded87f45489e6d84f23de6ed26).

I would open a PR, but apparently I don't have permission for that.

**Comment by wender** [comment]
@valentino-amadeus https://www.notion.so/vtexhandbook/How-to-set-up-the-service-json-on-your-node-app-83a6c3c67503415c872f51412eed74d6 is this example wrong?
![image](https://user-images.githubusercontent.com/24723/110708953-3bbc9380-81da-11eb-8d17-615976c5bb2a.png)

**Comment by valentino-amadeus** [comment]
It isn't, @wender. In the example, the app is requesting `2000` millicores of cpu. Under normal circumstances, you can request up to `800` millicores, but there are some apps that have extended permission - and can request up to `2000`.

**Comment by valentino-amadeus** [comment]
I'm getting back here to remind you about this issue. 
Because of the bound on the amount of cpu that reviews-and-ratings can request, the clusters are allocating `800m` of cpu to each of the app's pods (pod ~ instance), instead of the value that's declared in the app's service.json (`2500m`). I don't think you should change this. In fact, it is common to see one of the app's instances using almost as much cpu as the `800m` it gets. 
<sub>In the image below, the metrics for the last 6 hours.</sub>
<img width="1768" alt="Captura de Tela 2021-03-16 às 09 14 26" src="https://user-images.githubusercontent.com/67928158/111307723-9d488c00-8638-11eb-9ad4-dbec1c96196c.png">

But I do think it would be good to adjust the service.json of this app. The `250` value in the `cpu` field can be replaced with `80`. It would avoid future confusion and ensure that the clusters never allocate more than `800m` of cpu to reviews-and-ratings, even if the bound we currently have gets removed or increased.
